name: Compile, lint and test code

on:
  push:
    branches:
      - main
  pull_request:
    types: [synchronize, opened]

jobs:
  compile-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Compile code
        run: yarn tsc --skipLibCheck
      - name: Lint code
        run: yarn lint
      - name: Test code
        run: yarn test
